---
title: "Trrendy | Airbnb Price Predicter"
subtitle: "Travel Savvy with Price Savvy"
---

## Hello and welcome!

I'm Watson Van Archer, a dedicated student currently enrolled in the Master of Urban Spatial Analytics (MUSA) program at the University of Pennsylvania. 

Over the past four months, my journey in the world of geospatial has been nothing short of exhilarating. I've delved deep into various topics like API integration, web scraping, and the fascinating realm of machine learning. Each of these areas has not only piqued my interest but also significantly enhanced my skill set.

This website marks a personal milestone for me—it's the first I've built independently. It serves as a testament to the knowledge and experience I've gained and a canvas where I bring my learning to life.

I owe a tremendous amount of gratitude to Professor Nick Hand, who teaches MUSA 5500. His rigorous Python study materials are unparalleled, and they've played a crucial role in shaping my understanding, especially in the geospatial field. Professor Hand's guidance has been a beacon, illuminating the path in my educational journey.

Through this website, I aim to showcase my projects, share insights, and connect with others who share a passion for technology and urban spatial analysis. Whether you're a fellow student, a professional in the field, or just curious about the intersection of technology and urban studies, I hope you find something here that inspires you.

## Find out more

The code for this Project is hosted on this GitHub page: [https://github.com/watsonva/MUSA-550-Final](https://github.com/watsonva/MUSA-550-Final).

Have an interest in diving deeper on the course I am taking? Take a look at [PENN MUSA 550: Fall 2023](https://github.com/MUSA-550-Fall-2023) to find out more.






 
